### ISSUE TITLE
 Add Screen for Creating OAuth Credentials

### ISSUE THREAD

**Issue by Gowtham029** [ligreman/king#35]
Currently, there is no user interface screen available for creating OAuth credentials for consumers. This makes it difficult for users to manage their OAuth credentials.

To enhance the user experience, I propose adding a new user interface screen that will allow users to easily create OAuth credentials for the consumers. This screen should include the following fields:

`name, client_id, client_secret, redirect_uris`

**Comment by ligreman** [comment]
Added in Release 3.0.8.
