### ISSUE TITLE
Add Kong`s loopback support

### ISSUE THREAD

**Issue by jeremyjpj0916** [ligreman/king#45]
Few things that would be needed to make this as good as Konga in my use cases:

1. Loopback support for the admin API, loopback support endpoint typically want authenticated so I would say allowing a configurable admin API endpoint that has a auth token or even a HS256 JWT token key/secret like Konga does would allow king a secure pattern to access a kong instance when not localized to its env. Otherwise need a way to password protect the UI itself so can't even use King without a login at least. Both of these feats are ideal.

2. Taking the approach of reading the plugins from the admin API and allowing dynamic populations of fields for create from their schema.lua outputs is a neat feature of Konga I think may be missing here.

If I come up with any others will add them in here, but with Konga getting no dev love this could become the new defacto OSS UI tooling people move to. Konga still works well though for even not being updated any for the time being.

**Comment by ligreman** [comment]
@jeremyjpj0916 Hi and thanks for the ideas.

### About 1: loopback

I understand that your proposal is configure the Kong API loopback (as explained in the docs https://docs.konghq.com/gateway/latest/production/running-kong/secure-admin-api/#kong-api-loopback), and then having a way to pass the secret token via url parameters or a header.

Thats very interesting, but I must think of a way to store the token (or auth data) securely. King does not have a backend (I think that Konga does) so its a little tricky "where to store data". One way could be to offer an auth form in the interface so you can input the auth information, and store it... the only place available is the browser (session storage, data storage, cookie....). I don't see another way.

The way I currently password protect my King deployment is: I use an apache to serve King, and I configured the mod_ldap module from apache to restrict access to the King virtualhost. You can use mod_auth or other modules to configure other auth methods.

But I'll investigate how can I store the token in the browser in a secure way so it cannot be tampered by another "malicious" javascript. But it would be imposible to avoid someone stole the token if they have access to your browser (any case, it's like other web applications, if your session token is stolen, so it's a common problem).


### About 2: dynamic plugin population

Sorry if I don't get your idea in the right way, but King's plugin forms (adding/editing plugins) are dynamic right now. When you add/edit a new plugin, King calls the admin API to get the plugin's schema, and creates the form fields dynamically (actually it's a pain in **** to get it working without errors). So I think what you comment is already covered by King.

Thanks!

**Comment by jeremyjpj0916** [comment]
@ligreman yep part one you got it, thats how I would approach it too let us submit the jwt key and secret and endpoint. Probs turn off tls verification for https endpoints is easiest too.

as for plugin dynamics thats cool you got that part figured out, its indeed what I was hoping for. We have been looking for a konga replacement of sorts with its libs being so outdated this tool interests me if you plan to maintain for awhile 😄.

**Comment by jeremyjpj0916** [comment]
Also loving the fact this runs from source super easy I am not running into any errors, just:
npm install
npm start

Then boom:

![image](https://github.com/ligreman/king/assets/31913027/092e96be-2eb5-460c-b017-e1fb00b74318)

Konga stack trace bombs for me right now attempting something similarly localhost. Once that admin loopback endpoint w some jwt creds being past gets added I will be happy to QA it for yah, something like:

![image](https://github.com/ligreman/king/assets/31913027/f7a30132-8d18-45b0-b20a-472ad7a3dabe)

@ligreman

**Comment by ligreman** [comment]
@jeremyjpj0916 Nice! That screenshot helps a lot.

If you have Konga deployed locally, could you look at the local storage or session storage (or cookies) in the browser? I would like to know where does Konga stores the Key and Secret.

**Comment by jeremyjpj0916** [comment]
@ligreman  I actually had a better quick and dirty approach if you were down to code it up to support it, seems to not work at the moment.. The tool is adding a trailing / to the network call oddly but maybe you can support this:

I tried like this with jwt auth token premade and passed as query parameter like this endpoint allows:

![image](https://github.com/ligreman/king/assets/31913027/5427d257-f08d-452a-b383-a6a7eb4123ae)

So URL like: https://gateway.com:443/admin-api?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBZG1pbkFQSUF1dGgiLCJpYXQiOm51bGwsImV4cCI6MTY4ODcxNjI3NCwiYXVkIjoiIiwic3ViIjoiIn0.FFuLYSUBEPSIElH6pOO05UqfqhAeYkhWt2AQ6Qp687c

Then say services was being called from your app, would do:
https://gateway.com:443/admin-api/services?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBZG1pbkFQSUF1dGgiLCJpYXQiOm51bGwsImV4cCI6MTY4ODcxNjI3NCwiYXVkIjoiIiwic3ViIjoiIn0.FFuLYSUBEPSIElH6pOO05UqfqhAeYkhWt2AQ6Qp687c

etc. 

Seems right now in network calls I see it adding a trailing / to the end of the jwt token URI elements, code should be smarter to put admin /uri/paths before any query parameters?

![image](https://github.com/ligreman/king/assets/31913027/1ed655ce-ea57-4c33-8f8d-29d1c14cde5d)

Then all I need to do is also running into CORS errors(didn't picture those but I see them) since the calls are coming from browser but to fix that I can just add CORS support to this proxy endpoint for origin * and localhost will work fine.

Think you can fix the trailing / and make the resource lookups behaved like I described? Much easier than building out the auth capability if you just let a token be set as a query parameter in the connection string box url you already have.

**Comment by ligreman** [comment]
@jeremyjpj0916 Yesterday I was thinking how to implement the loopback thing because it is very very interesting. I'll do something about it. Probably I'll make a new dialog to configure the authentication for the loopback, and store it in the localStorage. 

Must also warn users that they must be careful with this localStorage, because anyone sharing your PC will be able to get the credentials, and it is also vulnerable to XSS attacks (if someone get access to your King deployment and modify its javascript, could stole the credentials) so it is not the best way to protect the admin API.

And I'll take a look at that final '/', I don't remember if it's something I added for any reason...

As you say, the CORS errors are invebitable (from the Kings perspective). They must be corrected in the proxy or the app server (apache, nginx...). But that's the way it is recommended/supposed to work, so, no problem with that actually.

**Comment by jeremyjpj0916** [comment]
thanks for the hard work!
