### ISSUE TITLE
Implement pagination in all resources list

### ISSUE THREAD

**Issue by jujudellago** [ligreman/king#51]
install and setup were easy, love the UI, but I can't figure out how to display all my consumers... I have around 160'000 consumers in kong, but I can only get 1000 in king... is there a limit that can be set somewhere ?

**Comment by ligreman** [comment]
That's right @jujudellago, it is a bug in King (more than a bug, a mistake). I forgot I've settled 1000 items as limit per elements. My goal was to implement pagination but I forgot about it all this time.

I'll implement it next.

**Comment by ligreman** [comment]
Kong API does not follow any good-practises convention and makes the pagination a hell.

This will be a lot harder to implement that it would seem aparently. It will take time.
