### ISSUE TITLE
Okta integration

### ISSUE THREAD

**Issue by podkhapov-zefr** [ligreman/king#55]
Does King support Okta integration?

**Comment by ligreman** [comment]
@podkhapov-zefr I have not worked with Okta before but I think King should support the integration as described here:
https://github.com/tom-smith-okta/okta-api-center/tree/master/gateways/kong

It is based in the OpenID Kong plugin and King supports it, so teorically it should be possible to integrate with Okta. BTW the plugin is only for Kong paid Enterprise accounts.
